### PR TITLE
Boot sd

### PR DESCRIPTION
**Pull request by hzhuang1**

### CODE REVIEW

**Comment by hzhuang1** [comment]
OK. I'll change it.

**Comment by rsalveti** [comment]
Why not booting with grub as well? Otherwise people will not be able to easily change the boot path for SD card (we should also support the case where eMMC is only used to store the boot firmware).

**Comment by fboudra** [comment]
@rsalveti it's planned but not now

**Comment by hzhuang1** [comment]
Use https://github.com/96boards/edk2/pull/59 instead.

**Pull request closed without merging**
